project:
  type: website
  output-dir: docs
  resources:
    - "images/*"

website:
  title: "Questions de Neuro-Ergonomie"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Accueil
      - href: fmri-question.qmd
        text: "Analyse IRMf"
      - href: bci-question.qmd
        text: "Technologie ICM"
      - href: about.qmd
        text: À propos
  page-footer:
    left: "Neuro-Ergonomie - Hiver 2025"
    right:
      - icon: github
        href: https://github.com/
    background: light

format:
  html:
    theme:
      light: [litera, custom.scss]
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    page-layout: full

lang: fr
